name: CD - Build, Analyze and Push Docker image

on:
  push:
    branches:
      - main
      - release/**

jobs:
  build_analyze_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Install dependencies
        run: dotnet restore BEESHOP.MAIN.API.sln

      # # Analyse SonarQube
      # - name: SonarQube Begin Analysis
      #   uses: sonarsource/sonarqube-scan-action@master
      #   with:
      #     projectBaseDir: .
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #     SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      # - name: Build solution
      #   run: dotnet build BEESHOP.MAIN.API.sln --configuration Release --no-restore

      # - name: Test solution
      #   run: dotnet test BEESHOP.MAIN.API.sln --no-build --verbosity normal

      # - name: SonarQube End Analysis
      #   uses: sonarsource/sonarqube-quality-gate-action@master
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # Login Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Récupérer version du csproj
      - name: Get version
        id: version
        run: |
          VERSION=$(grep -oPm1 "(?<=<Version>)[^<]+" BEESHOP.MAIN.API/BEESHOP.MAIN.API.csproj)
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      # Build Docker
      - name: Build Docker image
        run: |
          docker build -t louis404/beeshop-main-api:${{ steps.version.outputs.VERSION }} .
          docker tag louis404/beeshop-main-api:${{ steps.version.outputs.VERSION }} louis404/beeshop-main-api:latest

      # Push Docker
      - name: Push Docker image
        run: |
          docker push louis404/beeshop-main-api:${{ steps.version.outputs.VERSION }}
          docker push louis404/beeshop-main-api:latest
